name: code style check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  pre-commit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.0
