name: code style check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  pre-commit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/supported-python
      id: pythons
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ steps.pythons.outputs.newest }}
    - uses: pre-commit/action@v3.0.1
